name: Run Terraform
on: workflow_dispatch
env:
  DT_VERSION: "1.58.0"
  DT_ADDITIONAL_CONFIG_TYPES: "dynatrace_dashboard" # Optional
  DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
  DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
  DYNATRACE_AUTOMATION_CLIENT_ID: ${{ secrets.DYNATRACE_AUTOMATION_CLIENT_ID }}
  DYNATRACE_AUTOMATION_CLIENT_SECRET: ${{ secrets.DYNATRACE_AUTOMATION_CLIENT_SECRET }}

jobs:
  Export-Configuration:
    environment: DUMMY
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: "Get Binary"
        run: wget https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/download/v${{env.DT_VERSION}}/terraform-provider-dynatrace_${{env.DT_VERSION}}_linux_amd64.zip
      
      - name: "Unzip Binary"
        run: unzip -n terraform-provider-dynatrace_${{env.DT_VERSION}}_linux_amd64.zip
      
      - name: "Rename Binary"
        env:
          DT_VERSION: "1.58.0"
        run: mv terraform-provider-dynatrace_v${{env.DT_VERSION}} terraform-provider-dynatrace
      
      - name: "Bulk Export"
        run: "./terraform-provider-dynatrace --export"
      
      - name: "Export non-default items"
        run: "./terraform-provider-dynatrace --export ${{env.DT_ADDITIONAL_CONFIG_TYPES}}"

      - name: "List files and folders"
        run: "ls -al"
      
      - name: "Commit files to repo"
        run: "git add configuration/* && git commit -m 'update backup' && git push"